### ISSUE TITLE
Proxy setting

### ISSUE THREAD

**Issue by ghost** [rignaneseleo/SlimSocial-for-Facebook#161]
It is sad that it is not possible to access FB via Tor (by setting custom proxy localhost:9050 or whatever port Tor is configured to use, and thus routing the program's traffic through it).
Not even with the new version, v10.0.1.

Please add custom proxy setting (address:port).
Would be fantastic to have it, and SlimSocial-for-Facebook would be the only FB client to have this great feature.

**Comment by rignaneseleo** [comment]
I'll add this on the next release. 

Is there a proxy I can use for testing?

**Comment by A-7666** [comment]
Oh, really looking forward! :-) 

> Is there a proxy I can use for testing?

Not really, Tor runs on a device locally, localhost.
Can just install Orbot and run it in proxy mode, then the proxy would be localhost:9050.
https://github.com/guardianproject/orbot/releases

**Comment by rignaneseleo** [comment]
ok thanks!

Does facebook.com run on TOR or you need the .onion domain?

**Comment by A-7666** [comment]
No .onion domain is not required, facebook.com opens normally with Tor.

FB does have an official .onion domain (for desktop website at least), but it is super slow.
So usually I just open the regular facebook.com (via Tor localhost proxy), nothing wrong and works allright.

(Maybe adding an advanced/privacy setting to choose between facebook.com and .onion could be added, but this is probably a different/separate feature request. I'm just looking for a custom proxy setting, but maybe someone else will see this thread and open a new issue for the facebook.com/.onion selection setting, who knows)

**Comment by rignaneseleo** [comment]
I pushed the custom proxy feature. 

Can you compile and test if it works correctly?

**Comment by rignaneseleo** [comment]
Try v10.0.2

**Comment by rignaneseleo** [comment]
the czech bug was my fault, and is fixed on the new version you can find in the releases. 

Can you please open a new issue with the other bug and more details? I think many users are experiencing the same bug but I don't...

**Comment by rignaneseleo** [comment]
Does the proxy work?

**Comment by kowith337** [comment]
Can I jam this issue too?
I though proxy will be work even I'm using certain VPN-based hosts protections, e.g. AdAway, NetGuard, personalDNSFilter, etc. to block contacting to Facebook directly and using proxy instead, but it still doesn't work as intended, the app seems using direct connections even I've turn proxy settings to on.

Note that proxy may work if I've exclude this app to be filtered (aka. allowlist/whitelist)

**Comment by rignaneseleo** [comment]
The custom proxy setting shipped in v10.0.2 and it is still in Settings today (`custom_proxy_ip` / `custom_proxy_port`, applied at startup by `_setupProxy`).

Please use version **26.09.03+128** or later. Open a new issue if the problem comes back.
